@startuml Zustandsdiagramm
' Preview durch <Alt>d

hide empty description
state AuthProvider {
AuthProvider : token
AuthProvider : writeAccess
state App {
    [*] --> [*]: Logout

    state SearchBook {
        [*] --> EnterSearchCriteria: Suchkriterien eingeben
        EnterSearchCriteria --> Waiting: Button "Suche"
        EnterSearchCriteria --> SearchBook: Button "Zurücksetzen"

        state SearchChoice <<choice>>
        Waiting --> SearchChoice: Suchergebnis eingetroffen

        state SearchResultTable {
            SearchChoice --> FoundBooks: Suchergebnisse gefunden
            SearchChoice --> NoResults: Keine Suchergebnisse gefunden
            NoResults --> [*]
        }
    }

    state Details {
        [*] --> ShowDetails: Details anzeigen
        ShowDetails --> EditBook: Button "Bearbeiten"
        ShowDetails --> DeleteBook: Button "Löschen"
    }

    state EditBook {
        [*] --> EditFields: Änderungen eintragen

        state UpdateChoice <<choice>>
        EditFields --> UpdateChoice: Button "Bearbeiten"
        UpdateChoice --> UpdateBook: valide Daten
        UpdateChoice --> UpdateError: fehlerhafte Daten
        UpdateError --> EditFields: Daten abändern
        UpdateBook --> EditBook: hochladen der Daten
    }

    [*] --> SearchBook: Navigationsleiste "Erweiterte Suche"
    FoundBooks --> Details: Suchergebnis auswählen

    [*] --> AddBook: Navigationsleiste "Neues Buch"

    state AddBook {
        [*] --> EnterBookDetails: Daten eines Buches eintragen

        state AddChoice <<choice>>
        EnterBookDetails --> AddChoice: Button "Buch anlegen"
        AddChoice --> CreateBook: valide Daten
        AddChoice --> CreateError: invalide Daten
        CreateError --> EnterBookDetails: Daten abändern
        CreateBook --> AddBook: Buch wird hochgeladen
    }
}
}

@enduml